### ISSUE TITLE
[어드민] 로그인 페이지 기능 테스트 정의

### ISSUE THREAD

**Issue by juju1997** [juju1997/basic-board-project-admin#29]
로그인 기능을 구현하기 위해 테스트가 필요한지 검토
어드민 회원기능과 인증을 준비

## TODO
* [x] 로그인 설정 및 테스트 검토
* [x] 어드민 회원 기능 검토
* [x] 인증 테스트 검토
