### ISSUE TITLE
[어드민] 데이터 베이스 접근 로직 테스트 정의

### ISSUE THREAD

**Issue by juju1997** [juju1997/basic-board-project-admin#8]
어드민 서비스 프로젝트에서 데이터베이스를 사용할 수 잇게끔 환경을 구성하고 테스트를 정의함

### TODO
* [x] DB 만들기
* [x] 계정 권한 주기
* [x] IDE 접근 환경 세팅
* [x] repository 코드 작성
* [x] 관련 테스트 작성
